[project]
id = ""
name = "task-tracker"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.external.google]
enabled = true
